name: Delete Releases with Tags Release and PRTBB

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete Releases with Tags Release and PRTBB
        env:
          GH_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          for TAG in Release PRTBB; do
            RELEASES=$(gh release list --repo diegolix29/shadPS4 --json tagName,id -q ".[] | select(.tagName == \"$TAG\") | .id")
            if [ -n "$RELEASES" ]; then
              for RELEASE_ID in $RELEASES; do
                echo "Deleting release with ID: $RELEASE_ID (Tag: $TAG)"
                gh release delete "$RELEASE_ID" --repo diegolix29/shadPS4 --yes
              done
            else
              echo "No releases found with tag: $TAG"
            fi
          done

      - name: Delete Tags Release and PRTBB
        env:
          GH_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          git fetch --prune --tags
          for TAG in Release PRTBB; do
            if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
              echo "Deleting tag: $TAG"
              git push origin --delete "$TAG"
            else
              echo "No tag found: $TAG"
            fi
          done
