name: Delete Release and PRTBB Binaries

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  delete_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete Releases with Tags Release and PRTBB
        env:
          GITHUB_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          for TAG in Release PRTBB; do
            RELEASE_ID=$(gh release list --repo diegolix29/shadPS4 --json tagName,id -q ".[] | select(.tagName == \"$TAG\") | .id")
            if [ ! -z "$RELEASE_ID" ]; then
              echo "Deleting release with tag $TAG (ID: $RELEASE_ID)"
              gh release delete "$TAG" --repo diegolix29/shadPS4 --yes
            else
              echo "No release found with tag: $TAG"
            fi
          done
        continue-on-error: true

      - name: Delete Artifacts from Previous Runs
        env:
          GITHUB_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          for ARTIFACT in Release PRTBB; do
            ARTIFACTS=$(gh api repos/diegolix29/shadPS4/actions/artifacts --jq ".artifacts[] | select(.name == \"$ARTIFACT\") | .id")
            for ID in $ARTIFACTS; do
              echo "Deleting artifact ID: $ID"
              gh api -X DELETE repos/diegolix29/shadPS4/actions/artifacts/$ID
            done
          done
        continue-on-error: true
