name: Delete Releases with Tags Release and PRTBB

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  delete-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Delete releases with specific tags
        env:
          GH_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          # Get all releases
          releases=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/diegolix29/shadPS4/releases")

          # Loop through each release and check if it has the specific tags
          for release in $(echo "$releases" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${release} | base64 --decode | jq -r ${1}
            }

            tag_name=$(_jq '.tag_name')
            release_id=$(_jq '.id')

            # Check if the release tag matches the desired tags
            if [[ "$tag_name" == "release-shadPS4" ]] || [[ "$tag_name" == "PRTBB-shadPS4" ]]; then
              echo "Deleting release with tag $tag_name"
              
              # Delete the release
              curl -X DELETE -H "Authorization: token $GH_TOKEN" \
                "https://api.github.com/repos/diegolix29/shadPS4/releases/$release_id"
            fi
          done
