name: Delete Releases with Tags Release and PRTBB

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete Releases with Tags Release and PRTBB
        env:
          GH_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          for TAG in Releases; do
            RELEASES=$(gh release list --repo diegolix29/shadPS4 --json tagName,tagName -q ".[] | select(.tagName == \"$TAG\") | .tagName")
            if [ -n "$RELEASES" ]; then
              for RELEASE_tagName in $RELEASES; do
                echo "Deleting release with tagName: $RELEASE_tagName (Tag: $TAG)"
                gh release delete "$RELEASE_tagName" --repo diegolix29/shadPS4 --yes
              done
            else
              echo "No releases found with tag: $TAG"
            fi
          done
