name: Delete Release and PRTBB

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete Releases with Tags Release and PRTBB
        env:
          GITHUB_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          for TAG in Release PRTBB; do
            RELEASE_ID=$(gh release list --repo diegolix29/shadPS4 --json tagName,id -q ".[] | select(.tagName == \"$TAG\") | .id")
            if [ ! -z "$RELEASE_ID" ]; then
              echo "Deleting release with tag $TAG (ID: $RELEASE_ID)"
              gh release delete "$TAG" --repo diegolix29/shadPS4 --yes
            else
              echo "No release found with tag: $TAG"
            fi
          done

      - name: Delete Tags Release and PRTBB
        env:
          GITHUB_TOKEN: ${{ secrets.SHADPS4_TOKEN_REPO }}
        run: |
          git fetch --prune --tags
          for TAG in Release PRTBB; do
            if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
              echo "Deleting tag: $TAG"
              git push origin --delete "$TAG"
            else
              echo "No tag found: $TAG"
            fi
          done
