name: Apagar Releases e Tags

on:
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurar GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh
        
    - name: Autenticar com GitHub CLI
      run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

    - name: Apagar todas as releases
      run: |
        # Listando todas as releases e apagando
        releases=$(gh release list --json "id" --jq ".[].id")
        for release in $releases; do
          gh release delete "$release" --yes
        done

    - name: Apagar todas as tags
      run: |
        # Listando todas as tags e apagando
        tags=$(git tag)
        for tag in $tags; do
          git push --delete origin "$tag"
          git tag -d "$tag"
        done
